"""
AUREX Spatial Intelligence
Perception Signals

Standard event names generated by perception modules.
"""

PERSON_DETECTED = "perception.person.detected"

PERSON_UPDATED = "perception.person.updated"

PERSON_LOST = "perception.person.lost"

OBJECT_DETECTED = "perception.object.detected"

OBJECT_UPDATED = "perception.object.updated"

OBJECT_LOST = "perception.object.lost"

GESTURE_DETECTED = "perception.gesture.detected"

FACE_DETECTED = "perception.face.detected"

EYE_SIGNAL_DETECTED = "perception.eye.signal"

POSTURE_CHANGED = "perception.posture.changed"

MOVEMENT_DETECTED = "perception.movement.detected"

ENVIRONMENT_CHANGED = "perception.environment.changed"